replicaCount: 3
image:
  repository: rodriguez22/portfolio  # Imagen del nuevo repo
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: NodePort
  port: 3000 # El puerto del contenedor Next.js
  nodePort: 30081
ingress:
  host: portfolio.jrodrodriguez.es # A reemplazar por el dominio real
  wwwHost: www.portfolio.jrodrodriguez.es
  clusterIssuer: letsencrypt-prod