apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-rodriguez-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rodriguez-22/portfolio.git' # Repo actualizado
    targetRevision: HEAD
    path: deploy/miportfolio 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: portfolio-rodriguez # Namespace actualizado
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true