services:
  portfolio-web:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    image: portfolio_rodriguez:latest
    container_name: ct_portfolio_rodriguez
    restart: always
    ports:
      # Next.js corre en el 3000 internamente
      - "${PORT:-3000}:3000"